# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-25 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=255)),
                ('in_reply_to_status_id', models.CharField(max_length=255)),
                ('in_reply_to_user_id', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('retweeted_status_id', models.CharField(max_length=255)),
                ('retweeted_status_user_id', models.CharField(max_length=255)),
                ('retweeted_status_timestamp', models.CharField(max_length=255)),
                ('expanded_urls', models.CharField(max_length=255)),
            ],
        ),
    ]
