# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-25 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetsDB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='retweeted_status_id',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='retweeted_status_timestamp',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='retweeted_status_user_id',
        ),
        migrations.AddField(
            model_name='tweet',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='responses',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweets',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tweet',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
