# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-25 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetsDB', '0002_auto_20170925_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
