# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-25 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetsDB', '0003_auto_20170925_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='responses',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='retweets',
            field=models.IntegerField(null=True),
        ),
    ]
